# Generated by Django 5.1.4 on 2025-02-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='Age'),
        ),
    ]
