# Generated by Django 5.1.4 on 2025-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identification number'),
        ),
    ]
